- app/assets/stylesheets/config/_colors.scss
> grey color variables

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> colors fix and footer added

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/config/_fonts.scss
New fonts and footer looking better and at the bottom
> fonts and footer

- app/assets/stylesheets/components/_footer.scss
> footer fix

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
> another footer fix

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_cardlocation.scss
- app/views/itineraries/show.html.erb
- app/views/pages/home.html.erb
Hey Guys,
Added some work on the show page - disregard homepage branch.
> updated show page of itinerary - no work on the home page

- app/assets/stylesheets/components/_cardlocation.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_timeline.scss
- app/views/itineraries/show.html.erb
@DiogoABastos here is a div & stylesheet to insert with javascript to build the timeline.
> added timeline code and styelsheets

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_carditinerary.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/itineraries_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/itinerary.rb
- app/views/itineraries/index.html.erb
- db/seeds.rb
index major changes and other small stuff on footer and banner
> some index stuff and small things

- app/assets/stylesheets/components/_carditinerary.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_indexpage.scss
> added index page file and messed around

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_new.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
1. Made the new design for Login, Signup and FYP pages
> Login, Signup and FYP pages

- app/helpers/application_helper.rb
- app/models/itinerary.rb
- app/views/itineraries/show.html.erb
Worked on this with Joao. Logic is sound still need to enable a button with route post clone of an itinerary.
> added code for cloning, still need to enable button and path

- app/assets/stylesheets/components/_carditinerary.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/assets/stylesheets/pages/_indexpage.scss
- app/controllers/itineraries_controller.rb
- app/views/itineraries/index.html.erb
- app/views/shared/_search.html.erb
> index and search

- app/assets/stylesheets/pages/_indexpage.scss
> index media queries

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_formitinerarynew.scss
- app/assets/stylesheets/components/_new.scss
- app/assets/stylesheets/components/_profile.scss
- app/views/devise/sessions/new.html.erb
> footer bugs

- app/controllers/itineraries_controller.rb
- app/models/itinerary.rb
- app/policies/itinerary_policy.rb
- app/views/itineraries/_horizontal_navbar.html.erb
- config/routes.rb
Hey guys,
Added the cloning feature in the navbar. This is version one, still need to do the following:
-add "COPY" to the itinerary name after to show user it's a copy
-stefan
> added cloning feature to navbar

- Gemfile
- Gemfile.lock
- app/controllers/itineraries_controller.rb
- app/controllers/locations_controller.rb
- app/models/itinerary.rb
- app/models/itinerary_tag.rb
- app/models/location.rb
- app/models/tag.rb
- app/views/itineraries/_itinerary_details.html.erb
- app/views/itineraries/_location.html.erb
- app/views/itineraries/_location_form.html.erb
- app/views/locations/_form.html.erb
- app/views/locations/show.html.erb
- db/migrate/20200309100659_drop_tags_table.rb
- db/migrate/20200309100721_drop_itinerary_tags_table.rb
- db/migrate/20200309110021_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
- db/migrate/20200309110022_add_missing_unique_indices.acts_as_taggable_on_engine.rb
- db/migrate/20200309110023_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
- db/migrate/20200309110024_add_missing_taggable_index.acts_as_taggable_on_engine.rb
- db/migrate/20200309110025_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
- db/migrate/20200309110026_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
- db/migrate/20200309111602_remove_category_from_location.rb
- db/schema.rb
- db/seeds.rb
> added tags on each location

- config/environments/production.rb
> cloudinary fix for heroku

- app/views/itineraries/index.html.erb
> map 100vh index

- app/assets/stylesheets/components/_profile.scss
- app/assets/stylesheets/pages/_indexpage.scss
- app/controllers/pages_controller.rb
- app/views/itineraries/index.html.erb
- app/views/pages/profile.html.erb
- db/schema.rb
1. Changed the profile page design.
2. Added the list of user's itineraries.
> Profile page changes

- app/assets/stylesheets/components/_new.scss
- app/views/devise/registrations/new.html.erb
1. Added First Name, Last Name, Username, Age and Gender fields to the signup form.
> New signup form fields

- app/assets/config/manifest.js
- app/views/pages/home.html.erb
1. Added a new background video.
> New background video

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/itineraries/_form.html.erb
1. Styled the page, where the user creates the trip.
> Create Trip Page

- db/schema.rb
- db/seeds.rb
> Creating seeds

- app/views/itineraries/show.html.erb
1. Killed the white corners around avatar on the Show page.
> Fixed other avatar issues
